# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Planet KiF
author: The KiF Clan
email: contact@wlbr.de
description: >- # this means to ignore newlines until "baseurl:"
  Keiner ist feige!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://planet-kif.de" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:  planetkif
linkedin_username:
stackoverflow_username:
google_analytics: UA-28222529-1
show_excerpts: true
twitter:
    username:
    card: summary
logo: /assets/logo.png

social:
    name: Ben Balter
    links:
      - https://github.com/planetkif
      #- https://www.facebook.com/ben.balter
      #- https://keybase.io/benbalter

#paginate: 5
#paginate_path: /page:num/

# jekyll_analytics:
#     GoogleAnalytics:          # Add, if you want to track with Google Analytics
#     id: UA-28222529-1          # Required - replace with your tracking id
#     anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

# Build settings
theme: minima

plugins:
  - jekyll-feed
  #- jekyll-analytics
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
